export const CURRENCY_LIST = [
  // --- ASIA & ASEAN ---
  {
    id: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    code: "IDR",
    locale: "id-ID",
    flag: "🇮🇩",
  },
  {
    id: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    code: "SGD",
    locale: "en-SG",
    flag: "🇸🇬",
  },
  {
    id: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    code: "MYR",
    locale: "ms-MY",
    flag: "🇲🇾",
  },
  {
    id: "THB",
    name: "Thai Baht",
    symbol: "฿",
    code: "THB",
    locale: "th-TH",
    flag: "🇹🇭",
  },
  {
    id: "VND",
    name: "Vietnamese Dong",
    symbol: "₫",
    code: "VND",
    locale: "vi-VN",
    flag: "🇻🇳",
  },
  {
    id: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    code: "PHP",
    locale: "en-PH",
    flag: "🇵🇭",
  },
  {
    id: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    code: "JPY",
    locale: "ja-JP",
    flag: "🇯🇵",
  },
  {
    id: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    code: "KRW",
    locale: "ko-KR",
    flag: "🇰🇷",
  },
  {
    id: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    code: "CNY",
    locale: "zh-CN",
    flag: "🇨🇳",
  },
  {
    id: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    code: "HKD",
    locale: "zh-HK",
    flag: "🇭🇰",
  },
  {
    id: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    code: "INR",
    locale: "en-IN",
    flag: "🇮🇳",
  },

  // --- AMERIKA ---
  {
    id: "USD",
    name: "US Dollar",
    symbol: "$",
    code: "USD",
    locale: "en-US",
    flag: "🇺🇸",
  },
  {
    id: "CAD",
    name: "Canadian Dollar",
    symbol: "C$",
    code: "CAD",
    locale: "en-CA",
    flag: "🇨🇦",
  },
  {
    id: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    code: "BRL",
    locale: "pt-BR",
    flag: "🇧🇷",
  },
  {
    id: "MXN",
    name: "Mexican Peso",
    symbol: "$",
    code: "MXN",
    locale: "es-MX",
    flag: "🇲🇽",
  },

  // --- EROPA ---
  {
    id: "EUR",
    name: "Euro",
    symbol: "€",
    code: "EUR",
    locale: "de-DE",
    flag: "🇪🇺",
  },
  {
    id: "GBP",
    name: "British Pound",
    symbol: "£",
    code: "GBP",
    locale: "en-GB",
    flag: "🇬🇧",
  },
  {
    id: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    code: "CHF",
    locale: "de-CH",
    flag: "🇨🇭",
  },
  {
    id: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    code: "RUB",
    locale: "ru-RU",
    flag: "🇷🇺",
  },
  {
    id: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    code: "TRY",
    locale: "tr-TR",
    flag: "🇹🇷",
  },

  // --- OCEANIA & MIDDLE EAST ---
  {
    id: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    code: "AUD",
    locale: "en-AU",
    flag: "🇦🇺",
  },
  {
    id: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    code: "NZD",
    locale: "en-NZ",
    flag: "🇳🇿",
  },
  {
    id: "SAR",
    name: "Saudi Riyal",
    symbol: "SR",
    code: "SAR",
    locale: "ar-SA",
    flag: "🇸🇦",
  },
  {
    id: "AED",
    name: "UAE Dirham",
    symbol: "AED",
    code: "AED",
    locale: "ar-AE",
    flag: "🇦🇪",
  },
];
