export const MONEY_TRACKER_EMOJIS = [
  // 🍕 Makanan & Minuman
  { id: 1, emoji: "🍔", label: "Makan Besar", category: "Food" },
  { id: 2, emoji: "🍕", label: "Pizza / Junk Food", category: "Food" },
  { id: 3, emoji: "🍜", label: "Mie / Ramen", category: "Food" },
  { id: 4, emoji: "🥗", label: "Makanan Sehat", category: "Food" },
  { id: 5, emoji: "☕", label: "Kopi / Cafe", category: "Food" },
  { id: 6, emoji: "🍵", label: "Teh", category: "Food" },
  { id: 7, emoji: "🍦", label: "Dessert / Es Krim", category: "Food" },
  { id: 8, emoji: "🍰", label: "Kue / Snack", category: "Food" },
  { id: 9, emoji: "🍱", label: "Makan Siang Kantor", category: "Food" },
  { id: 10, emoji: "🍳", label: "Sarapan", category: "Food" },
  { id: 11, emoji: "🍺", label: "Alkohol / Bar", category: "Food" },
  { id: 12, emoji: "🥤", label: "Minuman Dingin", category: "Food" },
  { id: 13, emoji: "🍎", label: "Buah-buahan", category: "Food" },
  { id: 14, emoji: "🥦", label: "Sayur / Belanja Dapur", category: "Food" },
  { id: 15, emoji: "🍫", label: "Cokelat / Jajanan", category: "Food" },

  // 🏠 Kebutuhan Rumah & Rutinitas
  { id: 16, emoji: "🏠", label: "Sewa Rumah", category: "Housing" },
  { id: 17, emoji: "⚡", label: "Listrik", category: "Housing" },
  { id: 18, emoji: "💧", label: "Air", category: "Housing" },
  { id: 19, emoji: "📶", label: "WiFi", category: "Housing" },
  { id: 20, emoji: "📱", label: "Pulsa / Data", category: "Housing" },
  { id: 21, emoji: "🗑️", label: "Iuran Kebersihan", category: "Housing" },
  { id: 22, emoji: "🛋️", label: "Furniture", category: "Housing" },
  { id: 23, emoji: "🧼", label: "Sabun / Laundry", category: "Housing" },
  { id: 24, emoji: "🕯️", label: "Gas", category: "Housing" },
  { id: 25, emoji: "🔑", label: "Service", category: "Housing" },

  // 🚗 Transportasi
  { id: 26, emoji: "🚗", label: "Bensin", category: "Transport" },
  { id: 27, emoji: "🏍️", label: "Ojek Online", category: "Transport" },
  { id: 28, emoji: "🚲", label: "Sepeda", category: "Transport" },
  { id: 29, emoji: "🚌", label: "Bus", category: "Transport" },
  { id: 30, emoji: "🚆", label: "Kereta Api", category: "Transport" },
  { id: 31, emoji: "🚕", label: "Taksi", category: "Transport" },
  { id: 32, emoji: "✈️", label: "Tiket Pesawat", category: "Transport" },
  { id: 33, emoji: "🚢", label: "Kapal Laut", category: "Transport" },
  { id: 34, emoji: "🅿️", label: "Parkir", category: "Transport" },
  { id: 35, emoji: "🛠️", label: "Servis Kendaraan", category: "Transport" },

  // 🛍️ Belanja & Gaya Hidup
  { id: 36, emoji: "👕", label: "Pakaian", category: "Shopping" },
  { id: 37, emoji: "👟", label: "Sepatu", category: "Shopping" },
  { id: 38, emoji: "👜", label: "Tas / Aksesoris", category: "Shopping" },
  { id: 39, emoji: "💄", label: "Skincare", category: "Shopping" },
  { id: 40, emoji: "✂️", label: "Barbershop", category: "Shopping" },
  { id: 41, emoji: "💍", label: "Perhiasan", category: "Shopping" },
  { id: 42, emoji: "🕶️", label: "Kacamata", category: "Shopping" },
  { id: 43, emoji: "🎁", label: "Hadiah", category: "Shopping" },
  { id: 44, emoji: "🧸", label: "Mainan", category: "Shopping" },
  { id: 45, emoji: "🛒", label: "Supermarket", category: "Shopping" },

  // 🎮 Hiburan & Hobi
  {
    id: 46,
    emoji: "🎬",
    label: "Bioskop / Netflix",
    category: "Entertainment",
  },
  { id: 47, emoji: "🎮", label: "Game / Top Up", category: "Entertainment" },
  { id: 48, emoji: "🎵", label: "Musik", category: "Entertainment" },
  { id: 49, emoji: "📖", label: "Buku", category: "Entertainment" },
  { id: 50, emoji: "🏀", label: "Olahraga", category: "Entertainment" },
  { id: 51, emoji: "🏋️", label: "Gym", category: "Entertainment" },
  { id: 52, emoji: "🎸", label: "Alat Musik", category: "Entertainment" },
  { id: 53, emoji: "🎨", label: "Seni", category: "Entertainment" },
  { id: 54, emoji: "📷", label: "Fotografi", category: "Entertainment" },
  { id: 55, emoji: "🎡", label: "Taman Hiburan", category: "Entertainment" },

  // 🩺 Kesehatan
  { id: 56, emoji: "💊", label: "Obat-obatan", category: "Health" },
  { id: 57, emoji: "🏥", label: "Rumah Sakit", category: "Health" },
  { id: 58, emoji: "🦷", label: "Dokter Gigi", category: "Health" },
  { id: 59, emoji: "👓", label: "Optik", category: "Health" },
  { id: 60, emoji: "🧴", label: "Produk Kesehatan", category: "Health" },
  { id: 61, emoji: "🩹", label: "P3K", category: "Health" },
  { id: 62, emoji: "💆", label: "Spa / Pijat", category: "Health" },
  { id: 63, emoji: "🧪", label: "Cek Lab", category: "Health" },
  { id: 64, emoji: "🍎", label: "Vitamin", category: "Health" },
  { id: 65, emoji: "🦠", label: "Masker", category: "Health" },

  // 🎓 Pendidikan & Kerja
  { id: 66, emoji: "📚", label: "Buku Pelajaran", category: "Education" },
  { id: 67, emoji: "✏️", label: "Alat Tulis", category: "Education" },
  { id: 68, emoji: "🎓", label: "Biaya Kuliah", category: "Education" },
  { id: 69, emoji: "💻", label: "Software", category: "Work" },
  { id: 70, emoji: "📑", label: "Print / Copy", category: "Work" },
  { id: 71, emoji: "🎒", label: "Kursus", category: "Education" },
  { id: 72, emoji: "💼", label: "Perlengkapan Kerja", category: "Work" },
  { id: 73, emoji: "🏢", label: "Iuran Kantor", category: "Work" },
  { id: 74, emoji: "💡", label: "Investasi Ilmu", category: "Education" },
  { id: 75, emoji: "🖋️", label: "Legalitas", category: "Work" },

  // 💰 Keuangan & Investasi
  { id: 76, emoji: "📈", label: "Saham", category: "Finance" },
  { id: 77, emoji: "🪙", label: "Crypto", category: "Finance" },
  { id: 78, emoji: "🏦", label: "Bank", category: "Finance" },
  { id: 79, emoji: "💳", label: "Kartu Kredit", category: "Finance" },
  { id: 80, emoji: "📉", label: "Bayar Hutang", category: "Finance" },
  { id: 81, emoji: "🧧", label: "Zakat / Sedekah", category: "Finance" },
  { id: 82, emoji: "💸", label: "Pajak", category: "Finance" },
  { id: 83, emoji: "🛡️", label: "Asuransi", category: "Finance" },
  { id: 84, emoji: "🪙", label: "Recehan", category: "Finance" },
  { id: 85, emoji: "💵", label: "Cash", category: "Finance" },

  // 🐾 Hewan Peliharaan
  { id: 86, emoji: "🐱", label: "Makanan Kucing", category: "Pets" },
  { id: 87, emoji: "🐶", label: "Makanan Anjing", category: "Pets" },
  { id: 88, emoji: "🏥", label: "Vet", category: "Pets" },
  { id: 89, emoji: "🛁", label: "Grooming", category: "Pets" },
  { id: 90, emoji: "🎾", label: "Mainan Hewan", category: "Pets" },

  // 🌍 Lain-lain
  { id: 91, emoji: "🆘", label: "Darurat", category: "Other" },
  { id: 92, emoji: "🚬", label: "Rokok / Vape", category: "Other" },
  { id: 93, emoji: "💐", label: "Bunga", category: "Other" },
  { id: 94, emoji: "🎰", label: "Judi", category: "Other" },
  { id: 95, emoji: "🧺", label: "Donasi", category: "Other" },
  { id: 96, emoji: "📅", label: "Tagihan", category: "Other" },
  { id: 97, emoji: "🗳️", label: "Iuran Warga", category: "Other" },
  { id: 98, emoji: "📍", label: "Biaya Admin", category: "Other" },
  { id: 99, emoji: "❓", label: "Kategori Lain", category: "Other" },
  { id: 100, emoji: "✨", label: "Self Reward", category: "Other" },
];
