export const TOP_SPENDING_CATEGORIES = [
  {
    id: "food_beverage",
    label: "Food & Beverage",
    icon: "🍔",
    amount: "850K",
    bgColor: "#FFF4E5",
    shadowColor: "#f97316",
  },
  {
    id: "transport",
    label: "Transport",
    icon: "🚕",
    amount: "420K",
    bgColor: "#EEF2FF",
    shadowColor: "#6366f1",
  },
  {
    id: "shopping",
    label: "Shopping",
    icon: "🛍️",
    amount: "375K",
    bgColor: "#FDF4FF",
    shadowColor: "#a855f7",
  },
  {
    id: "bills_utilities",
    label: "Bills & Utils",
    icon: "🧾",
    amount: "310K",
    bgColor: "#F0F9FF",
    shadowColor: "#0ea5e9",
  },
  {
    id: "health_fitness",
    label: "Health",
    icon: "💊",
    amount: "200K",
    bgColor: "#F0FDF4",
    shadowColor: "#22c55e",
  },
  {
    id: "entertainment",
    label: "Entertainment",
    icon: "▶️",
    amount: "150K",
    bgColor: "#FFF1F2",
    shadowColor: "#f43f5e",
  },
];
