export const WALLET_LIST = [
  {
    id: "1",
    bank: "Mandiri",
    type: "Wallet",
    balance: "3.324.522,02",
    transactions: "323.000",
    themeId: "mint",
  },
  {
    id: "2",
    bank: "BCA",
    type: "Wallet",
    balance: "1.200.500.000,00",
    transactions: "1.200.000",
    themeId: "peach",
  },
  {
    id: "3",
    bank: "Wallet",
    type: "E-Wallet",
    balance: "850.000,00",
    transactions: "75.000",
    themeId: "sky",
  },
  {
    id: "4",
    bank: "Wallet",
    type: "E-Wallet",
    balance: "850.000,00",
    transactions: "75.000",
    themeId: "lavender",
  },
  {
    id: "5",
    bank: "Wallet",
    type: "E-Wallet",
    balance: "850.000,00",
    transactions: "75.000",
    themeId: "blush",
  },
  {
    id: "6",
    bank: "Wallet",
    type: "E-Wallet",
    balance: "850.000,00",
    transactions: "75.000",
    themeId: "sand",
  },
  // {
  //   id: "1",
  //   bank: "Mandiri",
  //   type: "Wallet",
  //   balance: "3.324.522,02",
  //   transactions: "323.000",
  //   themeId: "ocean",
  // },
  // {
  //   id: "2",
  //   bank: "BCA",
  //   type: "Wallet",
  //   balance: "12.500.000,00",
  //   transactions: "1.200.000",
  //   themeId: "forest",
  // },
  // {
  //   id: "3",
  //   bank: "Wallet",
  //   type: "E-Wallet",
  //   balance: "850.000,00",
  //   transactions: "75.000",
  //   themeId: "ember",
  // },
  // {
  //   id: "4",
  //   bank: "Wallet",
  //   type: "E-Wallet",
  //   balance: "850.000,00",
  //   transactions: "75.000",
  //   themeId: "violet",
  // },
  // {
  //   id: "5",
  //   bank: "Wallet",
  //   type: "E-Wallet",
  //   balance: "850.000,00",
  //   transactions: "75.000",
  //   themeId: "indigo",
  // },
  // {
  //   id: "6",
  //   bank: "Wallet",
  //   type: "E-Wallet",
  //   balance: "850.000,00",
  //   transactions: "75.000",
  //   themeId: "rose",
  // },
];
